name: CI for Spring Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: edu-user

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build application
        run: |
          ./gradlew clean build

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Gen Version
        id: gen-version
        run: |                                
          export TZ=Asia/Seoul                
          echo "VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME  }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Checkout Kubernetes manifest repository
        uses: actions/checkout@v3
        with:
          repository: NavyHubb/edu-k8s-manifest
          token: ${{ secrets.MANIFEST_GITHUB_TOKEN }}
          path: manifests

      - name: Update Kubernetes resources
        run: |
          echo "`ls`"
          cd edu-user/overlays/dev
          kustomize edit set image ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          cat kustomization.yaml

      - name: Commit files   # kubernetes 설정 파일 변경 사항을 커밋하고 manifest를 관리하는 GitHub 레포지토리에 푸시
        run: |
          cd manifests
          echo "`ls`"
          git config --global user.email "sngjae972@github.com"
          git config --global user.name "김성재"
          git commit -am "Update image tag"
          git push -u origin main
